### ISSUE TITLE
Preview procedure on README needs to be updated.

### ISSUE THREAD

**Issue by apinnick** [konveyor/forklift-documentation#329]
**Describe the bug**

Podman command for preview build no longer works because of a [new Git security feature](https://github.blog/2022-04-12-git-security-vulnerability-announced/). The podman container fails with a "fatal: unsafe repository" error and the workaround in the error message does not appear to work.

**Solution**

Provide instructions for installing Asciidoctor, running "$ asciidoctor master.adoc" in the document directory, and then opening the master.html file in a browser. Delete the master.html file so that it is not included in a PR.

It would also be a good idea to add "master.html" to the gitignore file.

**Comment by rokkbert** [comment]
I experienced this problem. Full error, repeated a few times, is:
```
fatal: unsafe repository ('/srv/jekyll' is owned by someone else)
    To add an exception for this directory, call:

      git config --global --add safe.directory /srv/jekyll
```    
At the end, and after some asciidoctor-warnings/errors, there is also this, possibly related, error:
```
jekyll 3.9.2 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
/usr/local/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir': Permission denied @ dir_s_mkdir - /srv/jekyll/_site (Errno::EACCES)
	from /usr/local/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
	from /usr/local/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
	from /usr/local/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
	from /usr/local/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
	from /usr/local/lib/ruby/3.1.0/fileutils.rb:211:in `each'
	from /usr/local/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/convertible.rb:226:in `write'
...
```
Afterwards there *is* html-documentation in the new _site directory, but after all the error messages that wasn't even expected.
